<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
	    <link rel="stylesheet" href="style.css"/>
	</head>


	<body>
        <!--Side menu-->
        <nav id="side-menu">   
            <div id="logo">learn3</div>
            <input id="search-field" type="search"  placeholder="Search...">
            <div class="divisor"></div>
            <img src="user.png">
            <div id="user-name" class="black-font">Lucas V. Oliveira</div>
            <div id="user-trackers" class="black-font">Trackers 1000</div>
            <div id="user-tracking" class="black-font">Tracking 1000</div>
            <div id="user-description" class="black-font">This is my description, I don't know what to write, so I am writing anything. This layout is historical cause it is the first layout of Learn3 Project. Cheers!</div>
            <div id="pta" class="black-font">Privacy | Terms | About</div>
            <div id="copyright" class="black-font">Copyright 2015 - Learn3</div>
        </nav>

        <!--General Content - Generated by PHP-->
        <section id="general-content">
            <!--<svg id="svgContainer"></svg>-->
        </section>


		<script src="jquery/jquery-2.1.4.min.js"></script>

		<script type="text/javascript" src="d3/d3.v3.min.js"></script>
		<script type="text/javascript" src="main.js"></script>
	</body>
</html>