<?php
    //Function for open specified file
    function OpenAndReadFile($fileName) {

        //@ -> suppress warnings

        $fileOpened = @fopen($fileName, "r");   //Open file specified
        $openResult = @fread($fileOpened, filesize($fileName)); //Read the complete file and get its content
        @fclose($fileOpened);   //close the file handle 

        //If no result were get, set msg
        if(!$openResult)
            $openResult = "OPENREAD_ERROR";

        return $openResult;
    }

    //Check if the user variable has been specified
    if(!isset($_GET['user']) || $_GET['user'] == "")
        exit("NO_USER_SPECIFIED");
    
    //Get the user files path using the GET variables
    $userPath = 'userdb'. DIRECTORY_SEPARATOR . $_GET['user'] . DIRECTORY_SEPARATOR;

    //If the user dir is not found, return error
    if(!is_dir($userPath))
        exit("USER_NOT_FOUND");

    //Open and read user-info xml file
    $userXmlString = OpenAndReadFile($userPath."user-info.xml");
    if($userXmlString == "OPENREAD_ERROR")
        exit("ERROR_WHILE_GATHERING_USER_DATA");

    //Get php object from the xml string
    $userObj = simplexml_load_string($userXmlString);

    //Generate user background color
    $gradientString = '180deg';
    
    //Iterate thry all the bgcolor tags and add it to the gradient string
    for($i = 0; $i < count($userObj->bgcolor); $i++) {
        $redComp = $userObj->bgcolor[$i]["red"];
        $greenComp = $userObj->bgcolor[$i]["green"];
        $blueComp = $userObj->bgcolor[$i]["blue"];

        $gradientString .= ', rgba(' . $redComp . ',' . $greenComp . ',' . $blueComp . ',.8)';                   
    }

    //Generate user-img path
    $userImgPath = str_replace('\\', '/', $userPath) .'user-img.jpg';

    //print_r($userImgPath);
    //echo $userXmlObj->name;

?>


<!DOCTYPE html>
<html>
	<head>
		<meta charset="UTF-8">
	    <link rel="stylesheet" href="style.css"/>
        <title><?php echo 'learn3 - ' . $userObj->name ?></title>
        <style>
            #side-menu {
                background: linear-gradient(<?php echo $gradientString ?>);
            }

            .user-img {
                background-image: url("<?php echo $userImgPath ?>");
                width: 200px;
                height: 200px;
                background-size: cover;
                background-repeat: no-repeat;
                background-position: 50% 50%;
                display: inline-block;
                box-shadow: 0px 0px 5px #fff;
                border: 2px solid #fff;
                border-radius: 100px;
            }
        </style>
	</head>

	<body>
        <!--Side menu-->
        <nav id="side-menu">   
            <div id="logo">learn3</div>
            <input id="search-field" type="search" placeholder="Search..."/>
            <div class="divisor"></div>
            <div class="user-img"></div>
            <div id="user-name" class="black-font"><?php echo $userObj->name ?></div>
            <div id="user-trackers" class="black-font">Trackers <?php echo $userObj->trackers ?></div>
            <div id="user-tracking" class="black-font">Tracking <?php echo $userObj->tracking ?></div>
            <div id="user-description" class="black-font"><?php echo $userObj->description ?></div>
            <div id="pta" class="black-font">Privacy | Terms | About</div>
            <div id="copyright" class="black-font">Copyright 2015 - Learn3</div>
        </nav>

        <!--General Content - Generated by PHP-->
        <section id="general-content">
            <!--<div class="button-save">Save Positions</div>-->
        </section>
        <script>
            var USER_PATH = "<?php echo str_replace('\\','/',$userPath); ?>";
        </script>

		<script src="jquery/jquery-2.1.4.min.js"></script>

		<script type="text/javascript" src="d3/d3.v3.min.js"></script>
		<script type="text/javascript" src="main.js"></script>
	</body>
</html>